//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Kantaiko.Controllers.Resources {
    using System;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Strings {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("Kantaiko.Controllers.Resources.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static string MissingRequiredParameter {
            get {
                return ResourceManager.GetString("MissingRequiredParameter", resourceCulture);
            }
        }
        
        internal static string ParameterConversationFailed {
            get {
                return ResourceManager.GetString("ParameterConversationFailed", resourceCulture);
            }
        }
        
        internal static string MatchingError {
            get {
                return ResourceManager.GetString("MatchingError", resourceCulture);
            }
        }
        
        internal static string MatchingException {
            get {
                return ResourceManager.GetString("MatchingException", resourceCulture);
            }
        }
        
        internal static string RequiredContextPropertyNotSet {
            get {
                return ResourceManager.GetString("RequiredContextPropertyNotSet", resourceCulture);
            }
        }
        
        internal static string ResolvedParameterNumberMismatch {
            get {
                return ResourceManager.GetString("ResolvedParameterNumberMismatch", resourceCulture);
            }
        }
        
        internal static string DuplicateCompositeProperty {
            get {
                return ResourceManager.GetString("DuplicateCompositeProperty", resourceCulture);
            }
        }
        
        internal static string DuplicateCompositeParameter {
            get {
                return ResourceManager.GetString("DuplicateCompositeParameter", resourceCulture);
            }
        }
        
        internal static string ServiceNotFound {
            get {
                return ResourceManager.GetString("ServiceNotFound", resourceCulture);
            }
        }
        
        internal static string ParameterValidationException {
            get {
                return ResourceManager.GetString("ParameterValidationException", resourceCulture);
            }
        }
        
        internal static string ParameterValidationFailed {
            get {
                return ResourceManager.GetString("ParameterValidationFailed", resourceCulture);
            }
        }
        
        internal static string NotMatched {
            get {
                return ResourceManager.GetString("NotMatched", resourceCulture);
            }
        }
        
        internal static string InvalidMatcherContextType {
            get {
                return ResourceManager.GetString("InvalidMatcherContextType", resourceCulture);
            }
        }
        
        internal static string InvalidValidatorValueType {
            get {
                return ResourceManager.GetString("InvalidValidatorValueType", resourceCulture);
            }
        }
        
        internal static string NoParameterConversionProperties {
            get {
                return ResourceManager.GetString("NoParameterConversionProperties", resourceCulture);
            }
        }
        
        internal static string ParameterConversionException {
            get {
                return ResourceManager.GetString("ParameterConversionException", resourceCulture);
            }
        }
        
        internal static string NoSuitableParameterConverter {
            get {
                return ResourceManager.GetString("NoSuitableParameterConverter", resourceCulture);
            }
        }
        
        internal static string NoTextPatternMatchProperties {
            get {
                return ResourceManager.GetString("NoTextPatternMatchProperties", resourceCulture);
            }
        }
        
        internal static string PipelineException {
            get {
                return ResourceManager.GetString("PipelineException", resourceCulture);
            }
        }
        
        internal static string ParentNotLinked {
            get {
                return ResourceManager.GetString("ParentNotLinked", resourceCulture);
            }
        }
        
        internal static string InvocationException {
            get {
                return ResourceManager.GetString("InvocationException", resourceCulture);
            }
        }
    }
}
